### PR TITLE
Ensure arrays of custom objects can be correctly deserialized

### PR DESCRIPTION
**Pull request by rpendleton**

### CODE REVIEW

**Comment by rpendleton** [comment]
In my case, I ran into this issue when deserializing a `Dictionary<string, object>` that had values of mixed custom types. When a value of a custom type was encountered for the first time, it was unexpectedly `null`, since `Read()` returns `null` for `BinaryLibrary` records.

I tried to write a simple test that serialized `object[]` with values of a custom type, but that didn't seem to cause the issue. I'll see if I can reproduce the issue in the test project using `Dictionary<string, object>` sometime tomorrow or Monday though.

**Comment by bbowyersmyth** [comment]
Thanks for the tip. I can reproduce it with a Dictionary<string, object> and have the test. Cheers for the fix.

**Comment by rpendleton** [comment]
Thanks! I noticed you published a new 1.0.1 version to NuGet, but it looks like that was built from the `users/bruceb/version` branch which doesn't have a recent version of `master` merged into it. This means the 1.0.1 version still has this issue. (Just to confirm, I also downloaded the package and looked at the DLL with ILSpy, and I see the older code without the fix.)

Based on the release note, I assume this wasn't intentional, so I figured I'd let you know.

**Comment by bbowyersmyth** [comment]
Thanks, Updated to 1.0.2

**Pull request merged**
